// <auto-generated />
using System;
using ArtisanShopAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtisanShopAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216064540_AddPricingConfig")]
    partial class AddPricingConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtisanShopAPI.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("ArtisanShopAPI.Models.CommissionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("estimated_price");

                    b.Property<string>("Features")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("features");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frame");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Shipping")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shipping");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size");

                    b.Property<string>("StoneCoverage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stone_coverage");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Treatments")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("treatments");

                    b.HasKey("Id");

                    b.ToTable("CommissionRequests");
                });

            modelBuilder.Entity("ArtisanShopAPI.Models.ContactInquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InquiryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContactInquiries");
                });

            modelBuilder.Entity("ArtisanShopAPI.Models.Painting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("details");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("image_url");

                    b.Property<int?>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("paintings", (string)null);
                });

            modelBuilder.Entity("ArtisanShopAPI.Models.PricingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FeatureClock")
                        .HasColumnType("numeric")
                        .HasColumnName("feature_clock");

                    b.Property<decimal>("FeatureDiamondStrips")
                        .HasColumnType("numeric")
                        .HasColumnName("feature_diamond_strips");

                    b.Property<decimal>("FeatureLeds")
                        .HasColumnType("numeric")
                        .HasColumnName("feature_leds");

                    b.Property<decimal>("FeatureStuds")
                        .HasColumnType("numeric")
                        .HasColumnName("feature_studs");

                    b.Property<decimal>("FrameLedMirror")
                        .HasColumnType("numeric")
                        .HasColumnName("frame_led_mirror");

                    b.Property<decimal>("FrameLedWooden")
                        .HasColumnType("numeric")
                        .HasColumnName("frame_led_wooden");

                    b.Property<decimal>("FrameMirror")
                        .HasColumnType("numeric")
                        .HasColumnName("frame_mirror");

                    b.Property<decimal>("FrameWooden")
                        .HasColumnType("numeric")
                        .HasColumnName("frame_wooden");

                    b.Property<decimal>("ShippingDomestic")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_domestic");

                    b.Property<decimal>("ShippingInternational")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_international");

                    b.Property<decimal>("ShippingNorthAmerica")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_north_america");

                    b.Property<decimal>("SizeExtraLarge")
                        .HasColumnType("numeric")
                        .HasColumnName("size_extra_large");

                    b.Property<decimal>("SizeLarge")
                        .HasColumnType("numeric")
                        .HasColumnName("size_large");

                    b.Property<decimal>("SizeMedium")
                        .HasColumnType("numeric")
                        .HasColumnName("size_medium");

                    b.Property<decimal>("SizeSmall")
                        .HasColumnType("numeric")
                        .HasColumnName("size_small");

                    b.Property<decimal>("StoneHeavy")
                        .HasColumnType("numeric")
                        .HasColumnName("stone_heavy");

                    b.Property<decimal>("StoneLight")
                        .HasColumnType("numeric")
                        .HasColumnName("stone_light");

                    b.Property<decimal>("StoneMedium")
                        .HasColumnType("numeric")
                        .HasColumnName("stone_medium");

                    b.Property<decimal>("StoneNone")
                        .HasColumnType("numeric")
                        .HasColumnName("stone_none");

                    b.Property<decimal>("TreatmentGeode")
                        .HasColumnType("numeric")
                        .HasColumnName("treatment_geode");

                    b.Property<decimal>("TreatmentResin")
                        .HasColumnType("numeric")
                        .HasColumnName("treatment_resin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("PricingConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
